# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - db:/var/lib/redis/data
volumes:
  db:
    driver: local
  redis:
    driver: local
